trigger:
  branches:
    include:
    - main

resources:
  repositories:
    - repository: templates
      type: git
      name: Plumbing/core-templates
    - repository: rollup-plugin-builder
      type: git
      name: Open/rollup-plugin-builder

stages:
- template: stages/sync/sync.yml@templates  # Template reference
  parameters:
    checkout: rollup-plugin-builder
